/**
 * Build-time transform that replaces runtime-config-map.js with a
 * self-contained module exporting only the target runtime's config.
 *
 * Eliminates cross-directory require() calls to ../../../runtimes/,
 * which break when the file is copied into per-runtime output dirs.
 *
 * The generated module preserves the same public API surface:
 *   - getRuntimeConfig(name) — returns the config (throws if name doesn't match)
 *   - listRuntimeConfigs()   — returns [name]
 *   - RUNTIME_CONFIG_MAP     — frozen { [name]: config }
 *
 * @param {string} _content  — ignored; the entire file is replaced
 * @param {object} runtime   — the target runtime config object
 * @returns {string}
 */
function inlineRuntime(_content, runtime) {
  const serialized = JSON.stringify(runtime, null, 2);

  return `'use strict';

// Generated by inline-runtime transform — do not edit.
// Source runtime: ${runtime.name}

const config = ${serialized};

const RUNTIME_CONFIG_MAP = Object.freeze({
  [config.name]: config,
});

function getRuntimeConfig(name) {
  const entry = RUNTIME_CONFIG_MAP[name];

  if (!entry) {
    throw new Error(
      \`This build only supports runtime "\${config.name}", got "\${name}"\`
    );
  }

  return entry;
}

function getDefaultRuntimeConfig() {
  return config;
}

function listRuntimeConfigs() {
  return Object.keys(RUNTIME_CONFIG_MAP);
}

module.exports = {
  RUNTIME_CONFIG_MAP,
  getRuntimeConfig,
  getDefaultRuntimeConfig,
  listRuntimeConfigs,
};
`;
}

module.exports = inlineRuntime;
