/**
 * Canonical policy rules for Maestro command safety enforcement.
 * Used by:
 *   - claude/scripts/policy-enforcer.js (Claude Code PreToolUse hook)
 *   - policies/maestro.toml (Gemini CLI policy pack — generated by src/generator/policy-toml-emitter.ts)
 *
 * Rule shapes:
 *   { matchType: 'prefix' | 'regex' | 'word', pattern: string, tier: 'command', reason: string }
 */

export type PolicyRule = {
  matchType: 'prefix' | 'regex' | 'word';
  pattern: string;
  tier: 'command';
  reason: string;
};

const DENY_RULES = Object.freeze([
  { matchType: 'prefix', pattern: 'rm -rf', tier: 'command', reason: 'Recursive force delete' },
  { matchType: 'prefix', pattern: 'rm -fr', tier: 'command', reason: 'Recursive force delete (flag reorder)' },
  { matchType: 'prefix', pattern: 'sudo rm -rf', tier: 'command', reason: 'Privileged recursive force delete' },
  { matchType: 'prefix', pattern: 'sudo rm -fr', tier: 'command', reason: 'Privileged recursive force delete (flag reorder)' },
  { matchType: 'prefix', pattern: 'git reset --hard', tier: 'command', reason: 'Discards uncommitted changes' },
  { matchType: 'prefix', pattern: 'git checkout --', tier: 'command', reason: 'Discards uncommitted file changes' },
  { matchType: 'prefix', pattern: 'git clean -fd', tier: 'command', reason: 'Removes untracked files permanently' },
  { matchType: 'prefix', pattern: 'git clean -df', tier: 'command', reason: 'Removes untracked files permanently (flag reorder)' },
  { matchType: 'prefix', pattern: 'git clean -xfd', tier: 'command', reason: 'Removes untracked and ignored files permanently' },
  { matchType: 'prefix', pattern: 'git clean -xdf', tier: 'command', reason: 'Removes untracked and ignored files permanently (flag reorder)' },
  { matchType: 'regex', pattern: '<<', tier: 'command', reason: 'Heredoc corrupts structured content (YAML, Markdown, JSON) — use write_file instead' },
  { matchType: 'prefix', pattern: 'rm --recursive --force', tier: 'command', reason: 'Recursive force delete (long flags)' },
  { matchType: 'regex', pattern: '\\bfind\\b[^|;&]*\\s-delete\\b', tier: 'command', reason: 'find -delete removes files in bulk' },
  { matchType: 'regex', pattern: '\\bdd\\b[^|;&]*\\bof=/dev/', tier: 'command', reason: 'dd writing to a device destroys data' },
  { matchType: 'regex', pattern: '\\bmkfs(\\.[a-z0-9]+)?\\b', tier: 'command', reason: 'Formatting a filesystem destroys data' },
  { matchType: 'regex', pattern: '\\bshred\\b', tier: 'command', reason: 'shred irreversibly destroys file contents' },
  { matchType: 'regex', pattern: '\\btruncate\\b[^|;&]*-s\\s*0\\b', tier: 'command', reason: 'truncate -s 0 empties a file' },
  { matchType: 'regex', pattern: '\\bchmod\\b[^|;&]*-R[^|;&]*\\s0{3,4}\\b', tier: 'command', reason: 'Recursive chmod 000 locks out access' },
  { matchType: 'regex', pattern: '\\bgit\\s+push\\b[^|;&]*(--force\\b|\\s-f\\b)', tier: 'command', reason: 'Force push can overwrite remote history' },
  { matchType: 'regex', pattern: ':\\(\\)\\s*\\{\\s*:\\s*\\|\\s*:', tier: 'command', reason: 'Fork bomb' },
]) satisfies readonly PolicyRule[];

const ASK_RULES = Object.freeze([
  { matchType: 'word', pattern: 'tee', tier: 'command', reason: 'Writes to file and stdout' },
  { matchType: 'regex', pattern: '\\s>>?\\s|\\s>>?$|^>>?\\s|\\d>>?\\s', tier: 'command', reason: 'Shell output redirection' },
]) satisfies readonly PolicyRule[];

const KNOWN_UNENFORCED_RUNTIMES = Object.freeze(['codex']);
export { DENY_RULES, ASK_RULES, KNOWN_UNENFORCED_RUNTIMES };
